### ISSUE TITLE
sorry to dissrupt, but can you tell mayo to unblock me?

### ISSUE THREAD

**Issue by Mastercopper2346** [Pico8430/Indie-Cross-PE-Port#11]
do it when u can plz
he blocked me for no reason

**Comment by DaveFan19** [comment]
instructions unclear, tried to tell mayo that but my fridge just grew legs and arms and started attacking me. picture for more details:
![image](https://user-images.githubusercontent.com/99294235/174456945-3a16cff2-5cfd-475e-93de-d35ad78ca6e3.png)
